### ISSUE TITLE
Plans for rails 4.1

### ISSUE THREAD

**Issue by Crystark** [ifad/chronomodel#25]
As you said yourself, this isn't yet compatible with rails 4.1.
Is there anything planned about it ?

Thanks

**Comment by vjt** [comment]
Adding @epdejager to this discussion after noticing [the Rails 4.1 branch on her GitHub account](https://github.com/epdejager/chronomodel/tree/patch_rails_41) :smile:

**Comment by vjt** [comment]
Active Record 4.2 is now supported starting with version [0.9.0](https://github.com/ifad/chronomodel/releases/tag/v0.9.0).
4.1 can be supported with small changes, if any of you still require 4.1 support please reopen.

Enjoy :-)

**Comment by Crystark** [comment]
Excellent news ! Any particular notes to migrate from chronomodel 0.8.2 to 0.9.0 ?

**Comment by vjt** [comment]
@Crystark nothing particular. The database structure has not changed, nor the user-facing API.

An internals change that *may* affect you, if you were relying on it, is that as of now `ActiveRecord::Relation`s generated by ChronoModel do not alter the select list anymore. In 0.8.2 CM used to add an `as_of_time` column to the select list, in order carry along in scope chains the timestamp passed to `.as_of`.

This was both clumsy, and it also couldn't be preserved with new AR 4.2 internal semantics, so it was removed. But, as it was available in the select list, you *may* have code that references this virtual column - even though that's unlikely IMVHO.

On the other hand, the `.as_of_time` method on returned ActiveRecord instances works as before.

Let me know :-)
