### ISSUE TITLE
The validity is not converted to a range

### ISSUE THREAD

**Issue by orbanbotond** [ifad/chronomodel#267]
`Person::History.unscoped.where(hid: 72376).first.validity`
  Person::History Load (5.1ms)  SELECT "history"."people".* FROM "history"."people" WHERE "history"."people"."hid" = $1 ORDER BY "history"."people"."hid" ASC LIMIT $2  [["hid", 72376], ["LIMIT", 1]]
=> 
`"[\"2017-02-20 00:00:00\",\"2017-03-09 00:00:00\")"`

For other AR's they are converted:
`Person::History.unscoped.where(hid: 86869).first.validity`
  Person::History Load (5.8ms)  SELECT "history"."people".* FROM "history"."people" WHERE "history"."people"."hid" = $1 ORDER BY "history"."people"."hid" ASC LIMIT $2  [["hid", 86869], ["LIMIT", 1]]
=> `[2018-01-29 00:00:00 UTC, nil]`

rails 7.0.8
ruby 3.2.2

**Comment by tagliala** [comment]
The host application has a patch which is overloading Chronomodel's one, causing this issue

**Comment by tagliala** [comment]
Closing here because there was a monkey patch in an initializer inside the host application. 

We'll reopen as a different issue
