### ISSUE TITLE
Microseconds not matching in Ruby and PG

### ISSUE THREAD

**Issue by algodave** [ifad/chronomodel#32]
Seems like [Time#usec](http://ruby-doc.org/core-2.3.3/Time.html#method-i-usec) used in [Chronomodel::Conversions#time_to_utc_string](https://github.com/ifad/chronomodel/blob/master/lib/chrono_model/utils.rb#L15-L17) sometimes returns a different number than the one actually stored in PG.

This prevents `pred` and `succ` to be computed properly.

In the following example, I'm trying to fetch the most recent history record and its predecessor, but the `pred` method fails as it returns `nil`.

```ruby
record = MyModel.find(123)
# got the record
most_recent = record.history.last
# got the history record
most_recent.valid_from.usec
# => 129625
most_recent.pred
# => nil
```

In order to check that a predecessor actually exists, I computed it "manually" like this:

```ruby
computed_pred = 
  if record.history.count > 1
    record.history[record.history.count - 2]
  else
    nil
  end
```

This way, I got the history record and then I checked its `valid_to`'s microseconds:

```ruby
computed_pred.valid_to.usec
# => 129625
```

On the Ruby side, it is the same as `most_recent` record's `valid_from`. Where's the issue then? I checked on the PG side by executing the following query:

```sql
select validity from history.my_table where id=123 order by recorded_at;
```

and I got a result like this:

```
                       validity
------------------------------------------------------
 ["2012-03-10 00:00:00","2017-02-06 09:46:31.129626")
 ["2017-02-06 09:46:31.129626",)
(2 rows)
```

As you can see, **microseconds differ in their last digit**.

What happened? 

Chronomodel was able to fetch the `most_recent` record because it doesn't use any timestamp in that query's conditions. But, when asking for `most_recent.pred` it passes `most_recent.valid_from` to `Chronomodel::Conversions#time_to_utc_string` in order to build the query condition, so `'2017-02-06 09:46:31.129625'` is passed to PG, and then no results are returned.

I am on the [improve-amend-period](https://github.com/ifad/chronomodel/tree/improve-amend-period) branch with Ruby 2.3.3, PostgreSQL 9.4.9 and am using:

```
activerecord (5.0.1)
pg (0.19.0)
```

**Comment by vjt** [comment]
Problem identified. [This code](https://github.com/ifad/chronomodel/blob/master/lib/chrono_model/utils.rb#L10) needlessly uses floating-point math causing rounding errors. 

```ruby
>> t = '2017-02-06 09:46:31.129626'
=> "2017-02-06 09:46:31.129626"
>> t =~ ISO_DATETIME
=> 0
>> $7
=> ".129626"
>> $7.to_f
=> 0.129626
>> $7.to_f * 1_000_000
=> 129625.99999999999
>> ($7.to_f * 1_000_000).to_i
=> 129625
```

Changing the regexp to capture only what is after the `.` and then using integer-only conversion removes the problem entirely.

Now working on a test case.

**Comment by vjt** [comment]
@algodave please test and let me know, I will cut a release afterwards.
