### ISSUE TITLE
Latest version creates invalid structure.sql

### ISSUE THREAD

**Issue by Crystark** [ifad/chronomodel#33]
Hi,

Since we moved to the latest version and rails 4.2, the structure.sql get's messed up. We get a lot of lines with repeated "IF NOT EXISTS":

```
--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- Name: history; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS IF NOT EXISTS IF NOT EXISTS history;


--
-- Name: temporal; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS IF NOT EXISTS IF NOT EXISTS temporal;


SET search_path = public, pg_catalog;
```

Also the schema_migrations are repeated at the end of the file:

```
SET search_path TO public,temporal,history;

INSERT INTO schema_migrations (version) VALUES ('20130213145103');

INSERT INTO schema_migrations (version) VALUES ('20130213151701');

INSERT INTO schema_migrations (version) VALUES ('20130221092430');
SET search_path TO public,temporal,history;

INSERT INTO schema_migrations (version) VALUES ('20130213145103');

INSERT INTO schema_migrations (version) VALUES ('20130213151701');

INSERT INTO schema_migrations (version) VALUES ('20130221092430');
SET search_path TO public,temporal,history;

INSERT INTO schema_migrations (version) VALUES ('20130213145103');

INSERT INTO schema_migrations (version) VALUES ('20130213151701');

INSERT INTO schema_migrations (version) VALUES ('20130221092430');
```

An easy way to reproduce this is to call `bundle exec rake db:migrate` multiple times. Each time it'll add an "IF NOT EXISTS".

It seems linked to the following file:
https://github.com/ifad/chronomodel/blob/59f15cd608b8eed23d003b453c9b34863c0282f5/lib/chrono_model/schema_format.rake#L36

**Comment by vjt** [comment]
Thanks for reporting.

**Comment by Crystark** [comment]
Thanks for the quick action. I'm not sure though that this will fix the repeated schema_migrations at the end of the file as that is handled there:
https://github.com/ifad/chronomodel/blob/master/lib/chrono_model/schema_format.rake#L27

or am i not seing something ?
Thanks gain

**Comment by Crystark** [comment]
@vjt it actually looks like something is wrong in the PG execution as we always get `exit 1`

```
> pg_dump -f /data/home/me/main/db/structure.sql -U me -d me_db -x -s -O --schema=public --schema=temporal --schema=history... exit 1
```

**Comment by vjt** [comment]
OK, that explains why I am unable to reproduce the issue. The `PG.make_dump` calls `pg_dump`, that will truncate the target `structure.sql` file and re-write it. OTOH if `pg_dump` fails then the file will not be recreated. The rake task should abort when `pg_dump` fails.

Can you please run `pg_dump -f /data/home/me/main/db/structure.sql -U me -d me_db -x -s -O --schema=public --schema=temporal --schema=history` by hand and paste its output here?

**Comment by Crystark** [comment]
FYi this is what I get in the `developement log` when i execute the db:migrate

```
PG: exec pg_dump -f /data/home/lthoulon/www/netadge/bo/main/db/structure.sql -U lthoulon -d lthoulon_netadge_db -x -s -O --schema=public --schema=temporal --schema=history
PG: exit 1
PG: -----8<----- stderr ----->8-----
pg_dump: No matching schemas were found
PG: ----8<---- end stderr ---->8----
```

If i run directly `pg_dump -f /data/home/me/main/db/structure.sql -U me -d me_db -x -s -O --schema=public --schema=temporal --schema=history` it works and creates the file without the if not exists:

```
--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- Name: history; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA history;


--
-- Name: temporal; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA temporal;


SET search_path = public, pg_catalog;
```

**Comment by vjt** [comment]
Gotcha, fixing it, it is due to how parameter splitting is done in the exec function. Fixing it.

**Comment by Crystark** [comment]
@vjt just pulled the master and it works nice. Thanks for the fix. Looking forward to the release. 👍
