### ISSUE TITLE
Using `change_table` in a temporal table removes the temporal flag and `DROP`s the history table

### ISSUE THREAD

**Issue by MirkoMignini** [ifad/chronomodel#334]
Using ```change_table``` on a table that is already temporal apparently removes the temporal flag. Not sure if this is by design. 

I expect that this adds ```new_column```, leaving ```temporal_table_name``` as temporal
```ruby
change_table :temporal_table_name do |t|
  t.string :new_column, null: false
end
```

Instead, it removes the temporal tables.

Maybe this should remove temporal flag?

```ruby
change_table :temporal_table_name, temporal: false
```

**Comment by tagliala** [comment]
Don't tell this to others, but `change_table` actually `DROP`s history table 🤫

```
ctiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "history.countries" does not exist
LINE 10:  WHERE a.attrelid = '"history"."countries"'::regclass
                             ^

from ~/.rvm/gems/ruby-3.3.6/gems/activerecord-7.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec'
Caused by PG::UndefinedTable: ERROR:  relation "history.countries" does not exist
LINE 10:  WHERE a.attrelid = '"history"."countries"'::regclass
                             ^
```

**Comment by tagliala** [comment]
The comment is not clear

https://github.com/ifad/chronomodel/blob/e2c9dfc8b9a0d5a020acb6bc67a269d393d29f50/lib/chrono_model/adapter/migrations.rb#L67-L69

Demoting means setting temporal to `false`

**Comment by tagliala** [comment]
https://github.com/ifad/chronomodel/pull/97/files#diff-afc4366e02e584ce9ab38246551d93fd82feea53f06c6d158ab3a08c5dc23929

#97 contains a fix to this problem
