### ISSUE TITLE
Passing a column to `quote` has been deprecated

### ISSUE THREAD

**Issue by algodave** [ifad/chronomodel#36]
This occurs on the `rails5` branch:

`DEPRECATION WARNING: Passing a column to `quote` has been deprecated. It is only used for type casting, which should be handled elsewhere. See https://github.com/rails/arel/commit/6160bfbda1d1781c3b08a33ec4955f170e95be11 for more information. `

Involved line is [ChronoModel::Adapter#L704](https://github.com/ifad/chronomodel/blob/rails5/lib/chrono_model/adapter.rb#L704)

I've fixed the same deprecation occurring in `ChronoModel::TimeMachine` with 753f1cbf47b746c98b95717021936b94a3a0bbc9 but haven't figured out yet how to fix it in this case where we don't know the type of the column in advance.

**Comment by vjt** [comment]
Hints in #28 [on this comment](https://github.com/ifad/chronomodel/pull/28#issuecomment-288055773)

**Comment by pzac** [comment]
Fixed in https://github.com/ifad/chronomodel/pull/28

**Comment by vjt** [comment]
:+1:
