### ISSUE TITLE
Triggers body has to be updated on rename_table

### ISSUE THREAD

**Issue by algodave** [ifad/chronomodel#38]
On [rename_table](https://github.com/ifad/chronomodel/blob/master/lib/chrono_model/adapter.rb#L56), the body of `_insert`, `_update` and `_delete` triggers should be updated, as there are references to the old table name and sequence.

For example the `_insert` trigger should be amended in the following places:

* set new sequence name: [adapter.rb#L750](https://github.com/ifad/chronomodel/blob/master/lib/chrono_model/adapter.rb#L750)
* set new temporal table name in the `current` variable: [adapter.rb#L753](https://github.com/ifad/chronomodel/blob/master/lib/chrono_model/adapter.rb#L753)
* set new history table name in the `history` variable: [adapter.rb#L756](https://github.com/ifad/chronomodel/blob/master/lib/chrono_model/adapter.rb#L756)

**Comment by vjt** [comment]
Instead of amending the body, it may then make sense to drop the trigger functions and recreate them using `chrono_create_view_for`. WDYT?

**Comment by algodave** [comment]
@vjt Interesting! With your hint, I should even be able to do a PR to fix this!

**Comment by vjt** [comment]
:+1: send it along :-)
