### ISSUE TITLE
Nested includes still broken with `as_of`

### ISSUE THREAD

**Issue by pzac** [ifad/chronomodel#45]
`Foo.as_of(...).includes(:bar)` works; `Foo.as_of(...).includes(bar: :baz)` fails with `TypeError: no implicit conversion of Symbol into Integer`.

**Comment by lleirborras** [comment]
Seems to work
https://github.com/ifad/chronomodel/tree/as-of-includes

**Comment by lleirborras** [comment]
@pzac you where right, it fails with includes in a has_many throug
https://github.com/ifad/chronomodel/commit/911e9fef3b99d5df59a3df5a9dfa5922f26c5dc7

**Comment by vjt** [comment]
Fixed in #52, released as `v0.11.0`.
