### ISSUE TITLE
Why do you overwrite the existing db:structure:dump and load tasks?

### ISSUE THREAD

**Issue by quidproquo** [ifad/chronomodel#50]
Just curious as to why you are rolling your own version of the dump and load tasks. Why not extend/use the underlying PostgreSQLDatabaseTasks class?

**Comment by vjt** [comment]
This gen was born on Rails 3.2, and those classes didn't exist yet. I am more than inclined in removing dupe code, so feel free to send a pull req targeting the currently supported versions :)
