### ISSUE TITLE
Duplicates in db/structure.sql => `INSERT INTO "schema_migrations" (version) VALUES`

### ISSUE THREAD

**Issue by roschaefer** [ifad/chronomodel#54]
Thanks for this awesome gem!

Before we merge this gem into master, I would like to get a better understanding of some oddities:

1. A `db:migrate` on an empty database creates duplicates entries e.g. when a new team member checks out the repository. (Or more often when I do `bin/rails db:drop db:create db:migrate RAILS_ENV=test`). Is there a way to stop it? Or do the project maintainers have to watch out if somebody checks in the `db/structure.sql`?

**Comment by vjt** [comment]
The `db/structure.sql` should stay checked in, I suppose there is a bug somewhere creating dupe entries. I will try the rake tasks chain you reported and revert back.

Thanks! :)

**Comment by vjt** [comment]
Hi,

has this by any chance been solved by 0df58d3 in #60?

Thanks :-)

**Comment by roschaefer** [comment]
I just rebased https://github.com/roschaefer/rundfunk-mitbestimmen/pull/375 and pointed the gem `chrono_model` to the branch `feature/command-line-tests` and there you go: No duplicate entries anymore. This can be closed. (Reopen, if you think we need tests here)

**Comment by roschaefer** [comment]
Can we merge #60 and release? :heart_eyes:

**Comment by vjt** [comment]
Yes, sure thing. I will do it tomorrow first thing in the morning :-).

Cheers,
