### ISSUE TITLE
`bin/rspec` does not terminate when migrations are pending

### ISSUE THREAD

**Issue by roschaefer** [ifad/chronomodel#57]
When I create a new migration:
```
$ bin/rails g migration Whatever
```
Followed by a
```
$ bin/rspec
```

I see a lot of terminal output:
```
An error occurred while loading ./spec/requests/broadcasts_spec.rb.
Failure/Error: ActiveRecord::Migration.maintain_test_schema!
ActiveRecord::PendingMigrationError:
  Migrations are pending. To resolve this issue, run:
          bin/rails db:migrate RAILS_ENV=test
# /home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:576:in `check_pending!'
# /home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:589:in `load_schema_if_pending!'
# /home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:595:in `block in maintain_test_schema!'
```

and `rspec` hangs and continues to print that error over and over again to the terminal.

I have to terminate it manually with `Ctrl+C`. It's not a big deal of course, however it is worrying :smile: 

I thougt I would report that, too.

**Comment by vjt** [comment]
Thanks for the report. Definitely pending migrations should not interfere with the test suite. However I fear this is more of an rspec/rails issue, and I guess it is not an infinite loop but an error triggered for each one of the specs being run. I will check, thanks.

**Comment by roschaefer** [comment]
I encountered this error on a branch that does not have `chronomodel` in the Gemfile. Closing

**Comment by aradradev** [comment]
Hello @roschaefer and @vjt, I hope this message finds you all well.
Did someone happen to know how I could fix this error Pending migration? it is just pending with rspec test when I am trying to run that But It is working I can create, delete,  update,  and view it.

**Comment by roschaefer** [comment]
> Hello @roschaefer and @vjt, I hope this message finds you all well.
> Did someone happen to know how I could fix this error Pending migration? it is just pending with rspec test when I am trying to run that But It is working I can create, delete,  update,  and view it.

Hey, it's been a long time since I opened that issue. The application where I used this gem is now defunct so I'm not trying to fix this issue anymore. I'm afraid I can't help

**Comment by aradradev** [comment]
@roschaefer Thanks for the reply, It's OK I fixed the issue.
