### ISSUE TITLE
Cannot create historical data for testing

### ISSUE THREAD

**Issue by roschaefer** [ifad/chronomodel#65]
Is there a way to overwrite the `:validity` of the historical record when I set up test data with factories?

I don't have this problem in unit testing, because the miliseconds between two calls of `create(:whatever)` are enough to query my chrono-modeled model at different timestamps.

Now I'm doing a request spec and the supplied parameter does not have miliseconds. That should not be a problem, as I can just create a couple of records with a day in between each `created_at`, right? Wrong.

Here's what I get when I debug my test and say `Impression::History.all`:
```ruby
=> [#<Impression::History:0x000055e12391bbd0
  id: 6096,
  response: 1,
  amount: 0.2e1,
  user_id: 7031,
  broadcast_id: 4711,
  created_at: Sat, 25 Nov 2017 01:54:16 UTC +00:00,
  updated_at: Sat, 25 Nov 2017 01:54:16 UTC +00:00,
  fixed: nil,
  hid: 6113,
  validity: [2017-12-01 01:54:17 UTC, nil],
  recorded_at: Fri, 01 Dec 2017 01:54:17 UTC +00:00>,
 #<Impression::History:0x000055e12391a3e8
  id: 6097,
  response: 1,
  amount: nil,
  user_id: 7032,
  broadcast_id: 4711,
  created_at: Sun, 26 Nov 2017 01:54:16 UTC +00:00,
  updated_at: Sun, 26 Nov 2017 01:54:16 UTC +00:00,
  fixed: nil,
  hid: 6114,
  validity: [2017-12-01 01:54:17 UTC, nil],
  recorded_at: Fri, 01 Dec 2017 01:54:17 UTC +00:00>,
 #<Impression::History:0x000055e123918ea8
  id: 6098,
  response: 1,
  amount: 0.7e1,
  user_id: 7033,
  broadcast_id: 4711,
  created_at: Mon, 27 Nov 2017 01:54:16 UTC +00:00,
  updated_at: Mon, 27 Nov 2017 01:54:16 UTC +00:00,
  fixed: nil,
  hid: 6115,
  validity: [2017-12-01 01:54:17 UTC, nil],
  recorded_at: Fri, 01 Dec 2017 01:54:17 UTC +00:00>,
 #<Impression::History:0x000055e125697f60
  id: 6099,
  response: 1,
  amount: 0.8e1,
  user_id: 7034,
  broadcast_id: 4866,
  created_at: Tue, 28 Nov 2017 01:54:16 UTC +00:00,
  updated_at: Tue, 28 Nov 2017 01:54:16 UTC +00:00,
  fixed: nil,
  hid: 6116,
  validity: [2017-12-01 01:54:17 UTC, nil],
  recorded_at: Fri, 01 Dec 2017 01:54:17 UTC +00:00>,
[...]
```

As you can see, I can make the created record have the desired `created_at` attribute but the `validity` is still valid from today.

I don't want to use `sleep`.

**Comment by roschaefer** [comment]
Here's the PR I'm working on, including the test https://github.com/roschaefer/rundfunk-mitbestimmen/pull/437

**Comment by pzac** [comment]
Hi @roschaefer, I've usually been tackling this issue following this approach, which I took the liberty to enter as a wiki page:

https://github.com/ifad/chronomodel/wiki/Backfilling-history

Using `travel_to` would definitely be nicer. @vjt might chime in?

**Comment by roschaefer** [comment]
Long time no see, but your suggestions worked as expected, thanks @pzac!

I'm closing this, as I find the documentation sufficient enough.
