### ISSUE TITLE
drop_table doesn't delete related functions

### ISSUE THREAD

**Issue by pzac** [ifad/chronomodel#66]
```»  be rails db:migrate
== 20171208093005 DropStuff: migrating ========================================
-- drop_table(:performance_ratings)
   -> 0.0236s
== 20171208093005 DropStuff: migrated (0.0237s) ===============================
```
But then

```
select proname from pg_proc where proname like '%ratings%';
                proname
────────────────────────────────────────
 chronomodel_performance_ratings_delete
 chronomodel_performance_ratings_insert
 chronomodel_performance_ratings_update
(3 rows)
```

PG documentation says

> For user-defined functions, PostgreSQL tracks dependencies associated with a function's externally-visible properties, such as its argument and result types, but not dependencies that could only be known by examining the function body.

So we'll need to remove those functions manually

**Comment by vjt** [comment]
Fix released in [v0.12.3](https://github.com/ifad/chronomodel/releases/tag/v0.12.3).
