### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by deepj** [ifad/chronomodel#72]
I'd be in Chronomodel could support Rails 5.2 as well!

**Comment by joehorsnell** [comment]
Hi @vjt - what's the issue with CM on Rails 5.2? Do you know what works/doesn't work? Thanks

**Comment by vjt** [comment]
Hello @joehorsnell - no, sorry, I haven't yet time to review.

**Comment by vjt** [comment]
This travis build shows what's wrong: https://travis-ci.org/ifad/chronomodel/builds/383125821. AR internals change continuously and the `patches.rb` code is the weakest part of ChronoModel. To be continued.

**Comment by vjt** [comment]
Any help with this is more than welcome - for anybody who feels brave enough to dig into Active Record :-). To reproduce:

* `bundle --gemfile gemfiles/rails_5.2.gemfile`
* `export BUNDLE_GEMFILE=gemfiles/rails_5.2.gemfile`
* `bundle console`

❤️

**Comment by roschaefer** [comment]
`NULL_RELATION` was removed here: https://github.com/rails/rails/commit/2bfa2c02a891d4817832807343c6f1d56e9bae50#diff-8bdf4d71fc80d5866e82a8024bb148d2
