### ISSUE TITLE
Add clarity on Ruby version support

### ISSUE THREAD

**Issue by hlascelles** [ifad/chronomodel#74]
The README says `Active Record 4.2 or 5.0 (4.2 doesn't work with Ruby 2.4, though)`. 
This was written some time ago. 

Does it mean: `Active Record 4.2 or 5.0 (4.2 doesn't work with Ruby 2.4 and higher, though)`

ie, does Ruby 2.5 work?

**Comment by vjt** [comment]
Hello @hlascelles,

this is the currently tested AR & Ruby version matrix: https://travis-ci.org/ifad/chronomodel/builds/356493920

Rails 5.2 support is not ready yet, there's #72 open for that unfortunately.

We will strive to increase compatibility with more AR and Ruby versions, but I cannot provide you a timeline now.

**Comment by hlascelles** [comment]
Excellent, thanks!
